---
releases:
- name: packetbeat
  version: "0+dev.1"

addons:
- name: packetbeat
  jobs:
  - name: packetbeat
    release: packetbeat
    properties:
      packetbeat:
        protocols:
          http:
            ports: [8080,80,4222,2822,8081,443]
        elasticsearch:
          host: 192.168.1.15
