---
name: logsearch

releases:
  - name: logsearch
    version: latest

instance_groups:
  - name: elasticsearch_master
    jobs:
      - name: elasticsearch
    networks:
      - name: default
        static_ips: [10.244.0.101]
    instances: 1
    azs: [z1]
    persistent_disk_type: default
    vm_type: default
    stemcell: default
    properties:
      elasticsearch:
        node:
          allow_master: true
          allow_data: true
  - name: elasticsearch
    jobs:
      - name: elasticsearch
    networks:
      - name: default
    instances: 3
    azs: [z1]
    persistent_disk_type: default
    vm_type: default
    stemcell: default
    properties:
      elasticsearch:
        node:
          allow_data: true
  - name: kibana
    jobs:
      - name:  kibana
    instances: 1
    azs: [z1]
    vm_type: default
    stemcell: default
    networks:
      - name: default
  - name: enable_shard_allocation
    instances: 1
    lifecycle: errand
    vm_type: default
    stemcell: default
    azs: [z1]
    jobs:
      - {name: enable_shard_allocation}
    networks:
      - name: default
    properties:
      enable_shard_allocation:
        elasticsearch:
          master_node: 10.244.0.101

properties:
  kibana:
    elasticsearch:
      host: 10.244.0.101
  elasticsearch:
    cluster_name: packetbeat
    master_hosts: [10.244.0.101]

update:
  canaries: 0
  max_in_flight: 5
  serial: false
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest
