---
releases:
- name: packetbeat
  version: "0+dev.2"

addons:
- name: packetbeat
  jobs:
  - name: packetbeat
    release: packetbeat
    properties:
      packetbeat:
        elasticsearch:
          host: 10.244.0.101
